### PR TITLE
added department views

### PR DESCRIPTION
**Pull request by jessnswift**
```
git fetch --all
git checkout js_departmentview
code .
```

Please check to make sure I have everything coded correctly. 

- added department view

### CODE REVIEW

**Comment by teaglebuilt** [comment]
on models:
change supervisor field to employee 
delete budget field

fix template path on your view

**Comment by MatthewKelly12** [comment]
In department model:
remove budget
change supervisorId to employeeId
add  def __str__  to return self.name
maybe change max_length from 30 to 50

Views:
add import at top

**Comment by MatthewKelly12** [comment]
from HRIT. models import Department

**Comment by MatthewKelly12** [comment]
Looks good Jess
ready to merge

**Comment by MatthewKelly12** [comment]
👍

**Pull request merged**
